import AppKit
import ClipStackCore

/// Polls `NSPasteboard.general.changeCount` and captures new copies (PRD F1, F2).
///
/// There is no notification for pasteboard changes on macOS, so polling is the
/// only option; 0.4s is fast enough to feel instant and cheap enough to be free.
@MainActor
final class ClipboardMonitor {
    private let store: ClipboardStore
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Pasteboard types whose presence means "do not record this".
    /// Password managers and clipboard utilities set these by convention.
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    init(store: ClipboardStore) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        stop()
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // .common so polling continues while a menu or resize loop is tracking.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        capture()
    }

    private func capture() {
        guard let types = pasteboard.types else { return }
        let names = Set(types.map(\.rawValue))

        // Our own write, marked on the way out.
        if names.contains(Paster.internalType.rawValue) { return }
        if !names.isDisjoint(with: Self.privateTypes) { return }

        // Text wins when both are present: a copy from a rich editor carries an
        // image rendition too, and the text is what the user meant.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            store.insert(.text(string))
            return
        }

        if let image = readImage() {
            store.insertImage(
                pngData: image.png,
                thumbnailData: image.thumbnail,
                pixelWidth: image.width,
                pixelHeight: image.height
            )
        }
    }

    private func readImage() -> (png: Data, thumbnail: Data?, width: Int, height: Int)? {
        let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff)
        guard let data, let rep = NSBitmapImageRep(data: data) else { return nil }
        guard let png = rep.representation(using: .png, properties: [:]) else { return nil }
        return (
            png: png,
            thumbnail: Self.thumbnail(from: rep),
            width: rep.pixelsWide,
            height: rep.pixelsHigh
        )
    }

    /// A small PNG for list rendering, so the full image never needs to be in memory.
    private static func thumbnail(from rep: NSBitmapImageRep, maxEdge: CGFloat = 128) -> Data? {
        let width = CGFloat(rep.pixelsWide)
        let height = CGFloat(rep.pixelsHigh)
        guard width > 0, height > 0 else { return nil }

        let scale = min(1, maxEdge / max(width, height))
        let size = NSSize(width: max(1, (width * scale).rounded()),
                          height: max(1, (height * scale).rounded()))

        guard let target = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: Int(size.width),
            pixelsHigh: Int(size.height),
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ) else { return nil }
        target.size = size

        NSGraphicsContext.saveGraphicsState()
        defer { NSGraphicsContext.restoreGraphicsState() }
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: target)
        NSGraphicsContext.current?.imageInterpolation = .high
        rep.draw(in: NSRect(origin: .zero, size: size))

        return target.representation(using: .png, properties: [:])
    }
}
